export const weekData = [
  {
    day: "MON",
    date: 23,
    morning: "done",
    lunch: "done",
    dinner: "done",
  },
  {
    day: "TUE",
    date: 24,
    morning: "done",
    lunch: "miss",
    dinner: "done",
  },
  {
    day: "WED",
    date: 25,
    morning: "done",
    lunch: "partial",
    dinner: "miss",
    today: true,
  },
  {
    day: "THU",
    date: 26,
    morning: "done",
    lunch: "done",
    dinner: "partial",
  },
  {
    day: "FRI",
    date: 27,
    morning: "done",
    lunch: "done",
    dinner: "done",
  },
  {
    day: "SAT",
    date: 28,
    morning: null,
    lunch: null,
    dinner: null,
    weekend: true,
  },
  {
    day: "SUN",
    date: 29,
    morning: null,
    lunch: null,
    dinner: null,
    weekend: true,
  },
];