export const weekData = [
  {
    day: "MON",
    date: 11,
    morning: "done",
    lunch: "done",
    dinner: "done",
  },
  {
    day: "TUE",
    date: 12,
    morning: "done",
    lunch: "miss",
    dinner: "done",
  },
  {
    day: "WED",
    date: 13,
    morning: "done",
    lunch: "partial",
    dinner: "miss",
    today: true,
  },
  {
    day: "THU",
    date: 14,
    morning: "done",
    lunch: "done",
    dinner: "partial",
  },
  {
    day: "FRI",
    date: 15,
    morning: "done",
    lunch: "done",
    dinner: "null",
  },
  {
    day: "SAT",
    date: 16,
    morning: null,
    lunch: null,
    dinner: null,
    weekend: true,
  },
  {
    day: "SUN",
    date: 17,
    morning: null,
    lunch: null,
    dinner: null,
    weekend: true,
  },
];