spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: 12345
    driver-class-name: oracle.jdbc.OracleDriver

    # ddl-auto: update:
    # 서버 재시작해도 데이터 유지
    # 엔티티에 필드 추가하면 컬럼 자동 추가
    # 실습/개발 환경에 적합
    # 엔티티 없으면 자동 생성

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경(alter) 시 테이블 자동 수정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true #sql 보기 좋게 출력
        show_sql: true #실행 sql 콘솔에 표시

  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping_assistant #데이터베이스명

  security:
    jwt:
      secret: your-super-secret-key-that-is-at-least-64-bytes-long-for-hs512-to-work-correctly
      expiration: 86400000 #만료시간(24기간 = 밀리초)

openai:
  api-key: ${OPENAI_API_KEY:default} #api키
  model: gpt-3.5-turbo #모델 버젼
  max-tokens: 1000 #응답 길이

logging:
  level:
    org.hibernate.SQL: debug #SQL 쿼리 로그 출력

springdoc:
  swagger-ui:
    path: /swagger-ui.html #API 문서 접속 경로
    enabled: true
    use-root-path: true
  api-docs:
    path: /v3/api-docs
  show-actuator:
    true

    #단계별로 스페이스 2칸
    #탭 사용 금지
