spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC
    username: Project
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop	# 실서버에서는 validate로 설정해야 한다!
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true

  data:
    mongodb:
      host: localhost #배포할때는 실제 서버 주소가 들어감
      port: 27017
      database: shopping_assistant # 데이터베이스명

  security:
    jwt:
      secret: your-super-secret-key-that-is-at-least-64-bytes-long-for-hs512-to-work-correctly
      expiration: 86400000 #토큰 만료시간 (24시간 = 밀리초)

openai:
  api-key: ${OPENAI_API_KEY:default}
  model: gpt-3.5-turbo # 모델버젼
  max-tokens: 1000 #응답 길이

logging:
  level:
    org.hibernate.SQL: debug #SQL 쿼리 로그 출력

springdoc:
  swagger-ui:
    path: /swagger-ui.html # API 문서 접속 경로 

# 단계별로 스페이스 2칸
# 탭 사용금지
